"""индексы на sales для ускорения аналитики

Revision ID: 0ff0c95eb616
Revises: e7b3c5a9d2f4
Create Date: 2026-08-02 22:33:29.100285

"""

import sqlalchemy as sa

from alembic import op

revision = "0ff0c95eb616"
down_revision = "e7b3c5a9d2f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_sales_city_client_type", "sales", ["city", "client", "type"], unique=False
    )
    op.create_index("ix_sales_city_month", "sales", ["city", "month"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sales_city_month", table_name="sales")
    op.drop_index("ix_sales_city_client_type", table_name="sales")
    # ### end Alembic commands ###
