"""visit form fields: sku by line, people, comment, goal

Revision ID: 67216350be73
Revises: f275937bb327
Create Date: 2026-09-10 15:16:34.328108

"""

import sqlalchemy as sa

from alembic import op

revision = "67216350be73"
down_revision = "f275937bb327"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("visits", sa.Column("sku_classic", sa.Integer(), nullable=True))
    op.add_column("visits", sa.Column("sku_strong", sa.Integer(), nullable=True))
    op.add_column("visits", sa.Column("sku_light", sa.Integer(), nullable=True))
    op.add_column("visits", sa.Column("people_count", sa.Integer(), nullable=True))
    op.add_column("visits", sa.Column("comment", sa.String(), nullable=True))
    op.add_column("visits", sa.Column("goal", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visits", "goal")
    op.drop_column("visits", "comment")
    op.drop_column("visits", "people_count")
    op.drop_column("visits", "sku_light")
    op.drop_column("visits", "sku_strong")
    op.drop_column("visits", "sku_classic")
    # ### end Alembic commands ###
